<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once LIB_PATH. 'Zing/Packages/name2id_service/name2id_service_types.php';

$GLOBALS['name2id_service_CONSTANTS'] = array();

$GLOBALS['name2id_service_CONSTANTS']['INVALID_ID'] = -1;

?>
