<?php
$userID = $this->userID;
$errMsg = $this->errMessage;
$txs = $this->txs;
$tranx = $_REQUEST['tranx'];
?>

<?php require_once APPLICATION_PATH . 'includes/header.php'; ?>
<div class="right_mexu">
    <div class="box_mexu">
        <p><strong>Bạn đang xem chi tiết các giao dịch gần đây nhất</strong>

    </div>

    <div class="table_mexu">
        <div style='overflow:auto;max-height:450px'>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="lstitle" width="15%">Thời gian</td>
                    <td class="lstitle" width="10%">Loại</td>
                    <td class="lstitle" width="15%">Mã GD</td>
                    <td class="lstitle" width="10%">Giá trị GD (Zing Xu)</td>
                    <td class="lstitle" width="15%">Ứng dụng</td>
                    <td class="lstitle" width="10%">Tình trạng</td>
                    <td class="lstitle" width="25%">Mô tả</td>
                </tr>
                <?php if ($txs == null) {
                ?>
                    <tr>
                        <td colspan='7' align='center' style='height: 90px;font-weight: bold;'>
                            <strong style='color:#FF5A00'>KHÔNG TỒN TẠI GIAO DỊCH NÀO GẦN ĐÂY!</strong>
                        </td>
                    </tr>


                <?php } else {
                ?>

                <?php 
                    $i = 0;
                    //var_dump($txs);
			
                    $apps = array();
                    $appinfor = new AppInfor();
                    foreach ($txs as $tx) {
			$formatAmmount=Zing_Util_DataFormat::formatMoney($tx->amount);
                        //get application data
                        if (!isset($apps[$tx->agentID])) {
                            try {
                                $apps[$tx->agentID] = $appinfor->getAppName($tx->agentID);
                            } catch (Exception $e) {                                
                                
                            }
                        }
                        $class = '';
                        $i++;
                        if ($i % 2 == 0) {
                            $class = 'lssecond';
                        }
                ?>
                        <tr>
                            <td <?= $class ?> width="15%"><?php
		             echo date('H:i, d/m/Y',$tx->txTime);
                ?>
                    </td>
                    <td <?= $class ?>>
                        <?php  
                        $type = '';
                        $detail = '';                       
                        
                        switch ($tx->txType) {
                            case '101': $type = 'Nạp tiền';
                                $detail = 'Chuyển ' . '<span class="zc-noiconzc">' . $formatAmmount. '</span> Zing Xu vào tài khoản';

                                break;
                            case '102': $type = 'Chuyển tiền';
                                $detail = 'Được Chuyển ' . '<span class="zc-noiconzc">' .$formatAmmount . '</span> Zing Xu vào tài khoản';

                                break;
                            case '103': $type = 'Tặng tiền';
                                $detail = 'Được tặng ' . '<span class="zc-noiconzc">' .$formatAmmount. '</span> Zing Xu vào tài khoản';

                                break;
                            case '201': $type = 'Thanh toán';
                                $detail = 'Mua ' . $tx->itemQuantities . ' <b>' .$tx->itemNames  . '</b> tốn ' . '<span class="zc-noiconzc">' . $formatAmmount . '</span> Zing Xu';

                                break;
                            case '202': $type = 'Hoàn tiền';
                                $detail = 'Được hoàn lại ' . '<span class="zc-noiconzc">' .$formatAmmount. '</span> Zing Xu';
                                break;
                            case '2': 
                            {  
                            if($tx->amount>0){
                             $type = 'Thêm tiền';
                             }
                            else{
                            $type = 'Giảm tiền';
                            }
			    $detail =$tx->description;
			     break;
			    }
                        }
                        echo $type;
                        ?></td>
                    <td <?= $class ?>><?= $tx->txID ?></td>
                    <td <?= $class ?> style='text-align:center'><span class="zc-noiconzc"><?= $formatAmmount ?></span></td>
                    <td <?= $class ?>><?= $apps[$tx->agentID] ?></td>
                    <td <?= $class ?> style='text-align:center'>
                        <?php 
                        switch ($tx->responseCode) {
                            case '1':
                            case '3'://gd dang xu ly
                        ?><div class='zc-dxl'></div><?php
                                break;

                            case '2':
                                if ($tx->txType == '2' || $tx->txType == '101' || $tx->txType == '102' || $tx->txType == '103' || $tx->txType == '202') {
                                    //gd thanh cong
                        ?><div class='zc-gdtc'></div><?php
                                }
                                if ($tx->txType == '201') {//gd dang xu ly
                        ?><div class='zc-dxl'></div><?php
                                }
                                break;
                            case '101':
                            case '102':
                        ?><div class='zc-gdtc'></div><?php
                                break;
                            case '-103':
                            case '-104'://gd that bai & rollback
                                 $detail =$tx->description;
                        ?><div class='zc-gdtb'></div><?php
                                break;
                        }
                        ?>
                    </td>
                    <td <?= $class ?> style='text-align:left;padding-left:5px'><?php echo $detail ?></td>

                </tr>
                <?php } ?>
                <?php } ?>
            </table>
        </div>
    </div>
    <div><br><span class='zc-icon-title'> Ý nghĩa các ký hiệu: </span><span style="float:left">&nbsp;&nbsp;&nbsp;&nbsp;GD: Giao Dịch</span><span class="zc-gdtc"> Giao dịch thành công</span><span class="zc-dxl"> Giao dịch đang xử lý</span> <span class="zc-gdtb"> Giao dịch thất bại</span>	</div><div style='clear:both'></div>
    <div class='box_mexu'>
      <p>
	<strong>Các ứng dụng đang dùng Ví Zing Me</strong>
      </p>
    </div>
   <div id='zcproducts'>
<table width='100%'><tr><td width='30px'>
<div id='appshowback' style='display:none'>
<a href='#' onclick='appBack()'><img src='http://credits-me.zing.vn/images/app_go_back.png'></a>
</div>
</td><td width='657px'>

    <ul class='ImgGame' id='appshow'>
      
    </ul>
</td><td  width='30px'>
<div id='appshownext' style='display:none'>
<a href='#' onclick='appNext()'><img src='http://credits-me.zing.vn/images/app_go_forward.png'></a>
</div>
</td>
</tr>
</table>
    </div>
<script>
	apps=new Array();
<?php 
	$maxDisplayed=8;
	$currentDisplayed=0;
	$jsindex=-1;
	$appURLs=array();
    if(!empty($this->registedApps)){
      foreach($this->registedApps as $app){
      
	if($app->isEnabled!=1 || $app->appID=='tpvv' || $app->appID=='zing' || $app->appID=='admin' || isset($appURLs[''.$app->appURL])){
	continue;
	}
	$appURLs[''.$app->appURL]='1';
	$currentDisplayed++;
	if($currentDisplayed%$maxDisplayed==1){
	$jsindex++;
	?>
	apps[<?=$jsindex?>]=new Array();
	apps[<?=$jsindex?>].push(new Array('<?=$app->appURL?>','<?=$app->iconPath?>','<?=$app->appName?>','<?=$app->appDes?>'));
	<?php

	continue;
	}
	?>

	apps[<?=$jsindex?>].push(new Array('<?=$app->appURL?>','<?=$app->iconPath?>','<?=$app->appName?>','<?=$app->appDes?>'));
<?php
	}
	}
?>
currentPage=0;

function appNext(){
currentPage++;
renderApps();
}
function appBack(){
currentPage--;
renderApps();
}
function renderApps(){
	var html=new Array();
	if(currentPage>=apps.length){
		return;
	}
	var currentAppPage=apps[currentPage];
	var currentAppPage_length=currentAppPage.length;	
	for(var i=0;i<currentAppPage_length;i++){
		var currentApp=currentAppPage[i];
		html.push("<li><a target='_blank' title='");
		html.push(currentApp[3]);
		html.push("' href='");
		html.push(currentApp[0]);
		html.push("'><img src='http://pay-credits-me.zing.vn/images/");
		html.push(currentApp[1]);
		html.push("'></a><br><strong><a title='");
		html.push(currentApp[3]);
		html.push("' target='_blank' href='");
		html.push(currentApp[0]);
		html.push("'>");
		html.push(currentApp[2]);
		html.push("</a></strong></li>");
	}
	document.getElementById('appshow').innerHTML=html.join('');
	renderAppsNext();
	renderAppsBack();
}
function renderAppsNext(){
	
	if(currentPage<apps.length-1){
		document.getElementById('appshownext').style.display='block';
	}
	else{
		document.getElementById('appshownext').style.display='none';
	}
}
function renderAppsBack(){
	if(currentPage!=0){
		document.getElementById('appshowback').style.display='block';
	}
	else{
		document.getElementById('appshowback').style.display='none';
	}
}
renderApps();
</script>
    <?php require_once APPLICATION_PATH . 'includes/footer.php'; ?>

