<script src="<?php echo "http://widget.me.zing.vn";?>/js/zingme_widget_ex_1.3.min.js"></script>
<input type='button' onclick='resynnall()' value='All Syn Memcache and Database'>
<table class="mainTab" width="100%" border="0" cellpadding="0" cellspacing="0">
<tbody>
	<tr>
	    <td class="tabTit" width="5%">#</td>
	    <td class="tabTit" width="10%">AppId</td>
		<td class="tabTit" width="20%">App Name</td>
		<td class="tabTit" width="5%">Vị trí</td>	
<td class="tabTit" width="5%">Action</td>	
  	</tr>
<?php 

for($i=0;$i<count($this->memcacheData);$i++){//continue;
	$app=$this->memcacheData[$i];
	?>
<tr class="<?php if($i%2==0)echo "hligh1";else echo "hligh2";?>">
	    <td><?=$i+1?></td>
	    <td><?=$app[0]->appID?></td>
		<td><?=$app[0]->appName?></td>
		<td><?=empty($app[1])?"0":$app[1]?><?php if($app[0]->isEnabled=='0'){echo '(disable)';}?></td><td>&nbsp;&nbsp;
<a href='javascript:edit("<?=$app[0]->appID?>","<?=empty($app[1])?"0":$app[1]?>")'><img src='<?php echo IMAGE_URL;?>/zing_admin/sort_number.png'></a>&nbsp;&nbsp;
<a href='javascript:reload("<?=$app[0]->appID?>")'><img src='<?php echo IMAGE_URL;?>/zing_admin/reload.png'></a>

</td>
	     
  	</tr>
<?php
}
?>
</tbody>
</table>
<script>
function edit(appid,sortall){
var namea=prompt("Nhập vị trí mới cho ứng dụng "+appid,sortall);
if (namea!=null && namea!="")
  {
	$.post('appsortset',{"appid":appid,"sort":namea},
		function (data){
			if(data.length>0){
				alert(data);
			}
			else{
			document.location="";
			}
		});

  }
}
function reload(appid){
$.post('reload',{"appid":appid},
function (data){
if(data.length>0){
alert(data);
}
else{
document.location="";
}
});
}
function resynnall(){
$.post('resynnall',{},
		function (data){
			if(data.length>0){
				alert(data);
			}
			else{
			document.location="";
			}
		});
}
</script>

