<script src="<?php echo "http://widget.me.zing.vn";?>/js/zingme_widget_ex_1.3.min.js"></script>
Quản lý các khiếu nại của người dùng:<br>
<ul>
<li>1. Nhập username người dùng và mã giao dịch.</li>
<li>2. Nhấn Tìm Kiếm và chọn Revert giao dịch khi đã xác nhận với ứng dụng đối tác.</li>
</ul>
<form method='post' action=''>
<table><tr><td>User Name:</td><td><input type='text' id='username' name='username'></td></tr>
<tr><td>Mã giao dịch:</td><td><input type='text' id='tranxid' name='tranxid'></td></tr>
<tr><td></td><td><input type='submit' value='Tìm Kiếm'></td></tr>
</table>
</form>
<table class="mainTab" width="100%" border="0" cellpadding="0" cellspacing="0">
<tbody>
	<tr>
                    <td class="tabTit" width="15%">Thời gian</td>
                    <td class="tabTit" width="10%">Loại</td>
                    <td class="tabTit" width="15%">Mã GD</td>
                    <td class="tabTit" width="10%">Giá trị GD</td>
                    <td class="tabTit" width="15%">Ứng dụng</td>
                    <td class="tabTit" width="10%">Tình trạng</td>
		    <td class="tabTit" width="25">Action</td>
  	</tr>

</tbody>
</table>
