<?php
$param=$this->param;
$config = Zend_Registry::get('configuration');
$url=$config->admin->url;
?>
 <?php if(!isset($param['ajax'])){?>
<script src="<?php echo "http://widget.me.zing.vn";?>/js/zingme_widget_ex_1.3.min.js"></script>
Thống kê giao dịch người dùng trên hệ thống:<br>
<ul>
<li>1. Bắt buộc nhập username người dùng hay nhập mã giao dịch </li>
<li>2. Bắt buộc nhập khoãng thời gian để thống kê</li>
<li>3. Nhấn Thống kê theo chi tiết giao dịch.</li>
</ul>

<form method='post' action='tranxbyusersubmit2'>
<table><tr><td>User Name    </td><td><input type='text' id='username' name='username' value='<?=$param['username']?>'></td><td/><td/></tr>
<tr><td> hay Mã giao dịch </td><td><input type='text' id='tranxid' name='tranxid' value='<?=$param['tranxid']?>'></td><td/><td/></tr>
<tr><td>From <span class="require">*</span></td><td><input type='text' id='fromdate' name='fromdate' value='<?=$param['fromdate']?>'></td>
<td>To <span class="require">*</span></td><td><input type='text' id='todate' name='todate' value='<?=$param['todate']?>'></td></tr>
<tr><td></td><td><input type='submit' value='Thống Kê Chi Tiết'  onclick='document.getElementById("page").value=0'></td></tr>
</table>

<input type='hidden' id='page' name='page' value='<?=$param['page']?>'>	

<?php if(count($this->tranxs)!=0){
?>
<input type='submit' value='Cũ Hơn' onclick='document.getElementById("page").value=<?=$param['page']+1?>'>
<?php }?>
<?php if($param['page']!=1){?>
<input type='submit' value='Mới Hơn' onclick='document.getElementById("page").value=<?=$param['page']-1?>'>
<?php }?>
</form>
<?php }?>
<table class="mainTab" width="100%" border="0" cellpadding="0" cellspacing="0" >
<tbody>
	<tr height='30px'>	    
	 <td class="tabTit" width="13%">AppID</td>   
                    <td class="tabTit" width="13%">Thời gian</td>                   
                    <td class="tabTit" width="5%">Mã GD</td>
                    <td class="tabTit" width="9%">Giá trị GD</td>
		    <td class="tabTit" width="10%">Vật Phẩm</td>
                    <td class="tabTit" width="5%">Giá VP</td>
                    <td class="tabTit" width="5%">Số lượng</td>                    
                    <td class="tabTit" width="10%">Tình trạng</td>
  	</tr>
  	<?php
  	if(isset($this->tranxs)){
	  $i=0;
		foreach($this->tranxs as $txbyapp){
	  foreach($txbyapp as $tx){
	      $i++;
	      ?>
	     <tr <?php if($i%2==0)echo 'class="hligh2"';?>  >

	      <td align='center'><?=$tx['appID']?></td>
	     <td align='center'><?=$tx['txTime']?></td>
	    
                        <td align='center' ><?= $tx['refID'] ?></td>
                        <td style='text-align:center'><?= $tx['amount'] ?></td>
			<td style='text-align:center'><?= $tx['itemNames'] ?></td>
			<td style='text-align:center'><?= $tx['itemPrices'] ?></td>
			<td style='text-align:center'><?= $tx['itemQuantities'] ?></td>
                     
                       
                       <td <?= $class ?> style='text-align:center'>
                        <?php 
                        if($tx['resultCode']>1000 || ($tx['resultCode']==0 && $tx['appID']=='zing') || ($tx['resultCode']==0 && $tx['appID']=='admin')) {                            
                                
                        ?>Thành công<?php                             
                        }
 			if($tx['resultCode']==0 && ($tx['appID']!='zing' && $tx['appID']!='admin')) {                            
                                
                        ?>Đang XL<?php                             
                        }
			if($tx['resultCode']<-1000) {                            
                                
                        ?>Thất bại<?php                             
                        }
			if($tx['resultCode']==-108) {                            
                                
                        ?>Thành công(timeout)<?php                             
                        }
			if($tx['resultCode']<=-101  && $tx['resultCode']>=-107) {                            
                                
                        ?>Thất bại(<?=$tx['resultCode']?>)<?php                             
                        }
                        ?>
                    </td>
		
	     </tr>
	     <?php
	  }
  	}
	}
	?>

</tbody>
</table>

 <?php if(!isset($param['ajax'])){
  
?>

<script>

function getTranxDetail(tranxID,tranxType,txLocalTime){
    if( $('#row_'+tranxID).next().hasClass('temp')){
	$('#row_'+tranxID).next().html("<td align='center' ><img src='/images/zing_admin/indicator3.gif'></td>");
      }
      else{
      $('#row_'+tranxID).after("<tr class='temp'><td align='center'><img src='/images/zing_admin/indicator3.gif'></td></tr>");
      }

    $.get('<?=$url?>/app/tranxbyusersubmit', { ajax:1, tranxid:tranxID,tranxtype:tranxType, localtime: txLocalTime },
    function(data){
      if( $('#row_'+tranxID).next().hasClass('temp')){
	$('#row_'+tranxID).next().html("<td></td><td colspan='10' >"+data+"</td>");
      }else{
      $('#row_'+tranxID).after("<tr class='temp'><td></td><td colspan='10' >"+data+"</td></tr>");
      }
    });
  }
	$(function() {
		$( "#fromdate" ).datepicker({ dateFormat: 'yy-mm-dd' });$( "#todate" ).datepicker({ dateFormat: 'yy-mm-dd' });
	});
  
</script>
<?php
}
?>
