<!-- left menu -->
<div id="sidebar-left">			
    <h2>Payment Administrator</h2>
    <div id="admin_menu">
       	<ul class="menu">
            <li class="expanded"><a>Ứng Dụng</a></li>
            <ul>
                <li class="expanded"><a href="/app/index">Quản lý Ứng Dụng</a></li>
                <li class="expanded"><a href="/app/appsort">Sắp Xếp Ứng Dụng</a></li>	
                <li class="expanded"><a href="/app/registerapp">Thêm Ứng Dụng</a></li>
            </ul>
            <li class="expanded"><a>Người Dùng</a></li>
            <ul>
                <li class="expanded"><a href="/app/userbalance">Truy Vấn ZingXu</a></li>
                <li class="expanded"><a href="/app/useradjust">Thay Đổi ZingXu</a></li>
                <li class="expanded"><a href="/app/lastedtranx">Giao Dịch Gần Nhất</a></li>
                <li class="expanded"><a href="/app/tranxbyuser">TK Giao Dịch</a></li>
                <?php /*                 * <li class="expanded"><a href="/app/tranxbyuser2">TK Giao Dịch(BackUp)</a></li> */ ?>
            </ul>
            <li class="expanded"><a>Thống kê App</a></li>
            <ul>
                <!--<li class="expanded"><a href="/app/complaint">Quản lý Khiếu Nại</a></li>-->

                <li class="expanded"><a href="/app/tranxbyappsummary">Summary</a></li>
                <?php /* <li class="expanded"><a href="/app/tranxbyapp">Chi Tiết</a></li> */ ?>
                <li class="expanded"><a href="/app/tranxbyapp">Chi Tiết</a></li>
                <li class="expanded"><a href="/app/tranxfilter">GD đang xử lý</a></li>
                <li class="expanded"><a href="/app/autoreport">Auto Report</a></li>
            </ul>
            <li class="expanded"><a>Tài khoản Report</a></li>
            <ul>
                <li class="expanded"><a href="/app/appuser">Quản lý Tài Khoản</a></li>
                <li class="expanded"><a href="/app/appnewuser">Thêm Tài Khoản</a></li>
            </ul>
            <li class="expanded"><a>Tài khoản Mod Admin</a></li>
            <ul>
                <li class="expanded"><a href="/app/adminuser">Quản lý Tài Khoản</a></li>
                <li class="expanded"><a href="/app/adminnewuser">Thêm Tài Khoản</a></li>
            </ul>
            <?php /* <?php if($this->userrole<=2) {?><li class="leaf"><a href="log">Log</a></li><?php }?>
              <?php if($this->userrole==1) {?><li class="leaf last"><a href="user">User</a></li><?php }?>
              <? */ ?>
       	</ul>
    </div>
</div>
<!-- end left menu -->

<div id="content">
    <div id="centerCont">	
        <p></p>
        <iframe id="tranxfilter" src="<?php echo TRANXFILTER_URL; ?>" frameborder="0" style="width: 1000px;min-height: 1500px" align="center"></iframe>  
    </div>
</div>
