#!/bin/sh

/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-04-26
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-04-27
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-04-28
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-04-29
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-04-30
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-01
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-02
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-03
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-04
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-05
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-06
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-07
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-08
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-09
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-10
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-11
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-12
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-13
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-14
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-15
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-16
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-17
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-18
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-19
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-20
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-21
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-22
/zserver/php/bin/php /home/warmup_report_credits/CreditImporter.php production 2011-05-23

