<?xml version="1.0" encoding="UTF-8"?>
<definitions name="common_faults" targetNamespace="http://www.csapi.org/wsdl/parlayx/common/v2_0/faults" xmlns:parlayx_common_xsd="http://www.csapi.org/schema/parlayx/common/v2_1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema elementFormDefault="qualified">
         <xsd:import namespace="http://www.csapi.org/schema/parlayx/common/v2_1" schemaLocation="parlayx_common_types_2_2.xsd"/>
      </xsd:schema>
  </types>
  <message name="PolicyException">
    <part name="PolicyException" element="parlayx_common_xsd:PolicyException">
    </part>
  </message>
  <message name="ServiceException">
    <part name="ServiceException" element="parlayx_common_xsd:ServiceException">
    </part>
  </message>
</definitions>
