<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('ZCommon')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_ZCommon.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('ZCommon.so')) return;
    } else {
      if (!dl('ZCommon.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class ZCommon {
	static function zcommon_info() {
		return zcommon_info();
	}
}

/* PHP Proxy Classes */
class std__vectorT_int_t {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_ZCommon_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_ZCommon_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($n=null) {
		if (is_resource($n) && get_resource_type($n) === '_p_std__vectorT_int_t') {
			$this->_cPtr=$n;
			return;
		}
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_std__vectorT_int_t(); break;
		default: $this->_cPtr=new_std__vectorT_int_t($n);
		}
	}

	function size() {
		return std__vectorT_int_t_size($this->_cPtr);
	}

	function capacity() {
		return std__vectorT_int_t_capacity($this->_cPtr);
	}

	function reserve($n) {
		std__vectorT_int_t_reserve($this->_cPtr,$n);
	}

	function clear() {
		std__vectorT_int_t_clear($this->_cPtr);
	}

	function push($x) {
		std__vectorT_int_t_push($this->_cPtr,$x);
	}

	function is_empty() {
		return std__vectorT_int_t_is_empty($this->_cPtr);
	}

	function pop() {
		return std__vectorT_int_t_pop($this->_cPtr);
	}

	function get($i) {
		return std__vectorT_int_t_get($this->_cPtr,$i);
	}

	function set($i,$val) {
		std__vectorT_int_t_set($this->_cPtr,$i,$val);
	}
}

class std__vectorT_std__string_t {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_ZCommon_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_ZCommon_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($n=null) {
		if (is_resource($n) && get_resource_type($n) === '_p_std__vectorT_std__string_t') {
			$this->_cPtr=$n;
			return;
		}
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_std__vectorT_std__string_t();break;
		default: $this->_cPtr=new_std__vectorT_std__string_t($n);
		}
	}

	function size() {
		return std__vectorT_std__string_t_size($this->_cPtr);
	}

	function capacity() {
		return std__vectorT_std__string_t_capacity($this->_cPtr);
	}

	function reserve($n) {
		std__vectorT_std__string_t_reserve($this->_cPtr,$n);
	}

	function clear() {
		std__vectorT_std__string_t_clear($this->_cPtr);
	}

	function push($x) {
		return std__vectorT_std__string_t_push($this->_cPtr,$x);
	}

	function is_empty() {
		return std__vectorT_std__string_t_is_empty($this->_cPtr);
	}

	function pop() {
		return std__vectorT_std__string_t_pop($this->_cPtr);
	}

	function get($i) {
		return std__vectorT_std__string_t_get($this->_cPtr,$i);
	}

	function set($i,$val) {
		return std__vectorT_std__string_t_set($this->_cPtr,$i,$val);
	}
}

class std__mapT_int_std__string_t {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_ZCommon_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_ZCommon_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($arg1=null) {
		if (is_resource($arg1) && get_resource_type($arg1) === '_p_std__mapT_int_std__string_t') {
			$this->_cPtr=$arg1;
			return;
		}
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_std__mapT_int_std__string_t(); break;
		default: $this->_cPtr=new_std__mapT_int_std__string_t($arg1);
		}
	}

	function size() {
		return std__mapT_int_std__string_t_size($this->_cPtr);
	}

	function clear() {
		std__mapT_int_std__string_t_clear($this->_cPtr);
	}

	function get($key) {
		return std__mapT_int_std__string_t_get($this->_cPtr,$key);
	}

	function set($key,$x) {
		return std__mapT_int_std__string_t_set($this->_cPtr,$key,$x);
	}

	function del($key) {
		std__mapT_int_std__string_t_del($this->_cPtr,$key);
	}

	function has_key($key) {
		return std__mapT_int_std__string_t_has_key($this->_cPtr,$key);
	}

	function is_empty() {
		return std__mapT_int_std__string_t_is_empty($this->_cPtr);
	}
}

class std__mapT_std__string_std__string_t {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_ZCommon_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_ZCommon_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($arg1=null) {
		if (is_resource($arg1) && get_resource_type($arg1) === '_p_std__mapT_std__string_std__string_t') {
			$this->_cPtr=$arg1;
			return;
		}
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_std__mapT_std__string_std__string_t(); break;
		default: $this->_cPtr=new_std__mapT_std__string_std__string_t($arg1);
		}
	}

	function size() {
		return std__mapT_std__string_std__string_t_size($this->_cPtr);
	}

	function clear() {
		std__mapT_std__string_std__string_t_clear($this->_cPtr);
	}

	function get($key) {
		return std__mapT_std__string_std__string_t_get($this->_cPtr,$key);
	}

	function set($key,$x) {
		return std__mapT_std__string_std__string_t_set($this->_cPtr,$key,$x);
	}

	function del($key) {
		return std__mapT_std__string_std__string_t_del($this->_cPtr,$key);
	}

	function has_key($key) {
		return std__mapT_std__string_std__string_t_has_key($this->_cPtr,$key);
	}

	function is_empty() {
		return std__mapT_std__string_std__string_t_is_empty($this->_cPtr);
	}
}

class zcommon_StringHolder {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'value') return zcommon_StringHolder_value_set($this->_cPtr,$value);
		if ($var === 'thisown') return swig_ZCommon_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if (function_exists('zcommon_StringHolder_'.$var.'_set')) return true;
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		$func = 'zcommon_StringHolder_'.$var.'_get';
		if (function_exists($func)) {
			$r = call_user_func($func,$this->_cPtr);
			if (!is_resource($r)) return $r;
			$c=substr(get_resource_type($r), /* fix symbol confliction between modules */ 3);
			return new $c($r);
		}
		if ($var === 'thisown') return swig_ZCommon_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_zcommon_StringHolder') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_zcommon_StringHolder();
	}
}


?>
