#!/bin/sh
#
# Startup script for Main
export APPNAME=/ucom/upmonitor/client
#export APPNAME=/blog/me/ugc
export HOME=/data/projects/upmonitor_client
cd $HOME
export JMXHOST=127.0.0.1
export JMXPORT=8040
export APPENV=production
export CLASSMAIN=system.ServiceDaemon
export XMS=512M
export CONF=conf
export JARFILE=dist/upmonitor_client.jar
export JAVA_HOME="/usr/lib/jvm/default-java/"
pid_file=tmp/service.pid
log_file=tmp/service.log

# Arguments to pass to the JVM
#-Dhttp.proxyHost=10.30.22.23 -Dhttp.proxyPort=80 \
JVM_OPTS=" \
	-Dconfig=$CONF \
        -Dapppath=$HOME \
        -Dappenv=$APPENV \
	-Dzname=$APPNAME \
	-Dupmonitor=1 \
	-Dforeground=true \
	-Dhttp.proxyHost=10.30.12.30 \
	-Dhttp.proxyPort=81 \
	-Djzcommonx.version=1.0.0 \
	-Dzicachex.version=1.0.0 \
	-DzkHost=10.30.12.42 \
	-DzkPort=2181 \
	-Xmx$XMS \
        -XX:SurvivorRatio=8 \
        -XX:+UseParNewGC \
        -XX:+UseConcMarkSweepGC \
        -XX:+CMSParallelRemarkEnabled \
        -XX:MaxTenuringThreshold=1 \
        -XX:CMSInitiatingOccupancyFraction=75 \
        -XX:+UseCMSInitiatingOccupancyOnly \
        -XX:+HeapDumpOnOutOfMemoryError \
        -Djava.rmi.server.hostname=$JMXHOST \
        -Dcom.sun.management.jmxremote.port=$JMXPORT \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Dcom.sun.management.jmxremote.authenticate=false "

if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

case "$1" in
    start)
        # Main startup
        echo -n "Starting $APPNAME (port $JMXPORT): "
#        exec $JAVA $JVM_OPTS -jar  $JARFILE 
        exec $JAVA $JVM_OPTS -jar  $JARFILE > $log_file 2>&1 &
        [ ! -z $pid_file ] && printf "%d" $! > $pid_file
        echo "OK"
        ;;
    stop)
        # Main shutdown
        echo -n "Shutdown $APPNAME (port $JMXPORT): "
        kill `cat $pid_file`
        echo "OK"
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    status)
        ;;
    *)
        echo "Usage: `basename $0` start|stop|restart|reload"
        exit 1
esac
exit 0
