
<div id="sidebar-left">			
	<h2><?=$this->appname?></h2>
	<div id="admin_menu">
       	<ul class="menu">
	     
	      <li class="expanded">Thống kê App</li>
	      <ul>
              <li class="expanded"><a href="/app/tranxbyappsummary">Summary</a></li>
	     <?php /* <li class="expanded"><a href="/app/tranxbyapp">Chi Tiết</a></li>*/?>
	      </ul>
              
       	</ul>
	</div>
</div>
	
<div id="content">
<div id="centerCont">
<div id="divErr" name="divErr" class="divErr"></div>
<form name="frmChangePass" id="frmChangePass" action="" method="get">
<table class="mainTab" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td class="hligh2" width="20%"><label for="viewname">Current Password</label><span
				class="require">*</span></td>
			<td class="hligh2"><input name="txtCurrPass" id="txtCurrPass"
				style="width: 200px;" maxlength="50" title="Please Enter Current Password"
				class="required" type="password"></td>
		</tr>
		<tr>
			<td class="hligh1" width="20%"><label for="viewname">Password</label><span
				class="require">*</span></td>
			<td class="hligh1"><input name="txtNewPass" id="txtNewPass"
				style="width: 200px;" maxlength="50" title="Please Enter New Password"
				class="required" type="password"></td>
		</tr>
		<tr>
			<td class="hligh2" width="20%"><label for="viewname">Confirm Password</label><span
				class="require">*</span></td>
			<td class="hligh2"><input name="txtConfirmPass" id="txtConfirmPass"
				style="width: 200px;" maxlength="50"
				title="Please Enter Confirm Password" class="required"
				type="password"></td>
		</tr>
		<tr>
			<td class="hligh1"></td>
			<td class="hligh1"><input name="btnChangePass" id="btnChangePass"
				value="Change" class="button" type="button"></td>
		</tr>
	</tbody>
</table>
</form>
</div>
<!-- END centerCont --></div>
<!-- END content -->

<script type="text/javascript">
	$('#btnChangePass').click(function() {

		$("#divErr").html("");
		
		var currpassword = ($('#txtCurrPass').val());
		var password = ($('#txtNewPass').val());
		var confirmpassword = ($('#txtConfirmPass').val());
		var passlength = $('#txtNewPass').val().length;
		$.ajax({
			   type: "POST",
			   url: "changepass",
			   	data: { currpassword: currpassword, 
		   				password: password,
		   				confirmpassword: confirmpassword,
		   				passlength: passlength
		   				 },
			   	error: function (){
					alert("There's an unknown error occured!");
				},		   
			   	success: function(stringData){
					var obj = JSON.parse(stringData);
					if(obj.success==true)
					{
						alert("Change pass successfully");
						$('#txtCurrPass').val("");
						$('#txtNewPass').val("");
						$('#txtConfirmPass').val("");
					}
					else
					{
						alert("Change pass failed!");
						var divErrHTML = "";
						var index = 0;						
						for(index=0;index<obj.error.length;index++)
							divErrHTML += (index+1)+". "+obj.error[index]+"<br/>";
						$("#divErr").html(divErrHTML);
					}			
			   }
			 });
	});
</script>
