<?php
/*
 * Author: Khanv
 */

class Profanity
{  
	public static $profanityPatial = array(			
		"#zả zách#i",
		"#vkl#i",
		"#c.hó#i",
		"#lzzz#i",
		"#fuck#i",
		"#shit#i",
		"#buồi#i",
		"#địt#i",
		"#đụ#i",
		"#nứng#i",
		"#lồn#i",
		"#fuck#i",
		"#fucking#i",
		"#cock#i",
		"#bitch#i",
		"#cặc#i",
		"#cặt#i",
		"#kặc#i",
		"#Đụ#i",
		"#đéo#i",
		"#suck#i",
		"#dcm#i",
		"#DCM#i",
		"#vcl#i",
		"#bullshit#i",
		"#khốn nạn#i",
		"#đụ má#i",
		"#Đĩ#i",
		"#địt mẹ mày#i",
		"#đéo mẹ#i",
		"#đụ mẹ#i",
		"#lồn mẹ#i",
		"#lỗ đít#i",
		"#móc lồn#i",
		"#liếm lồn#i",
		"#ăn lồn#i",
		"#liếm lìn#i",
		"#mặt lìn#i",
		"#con phò#i",
		"#con kặc#i",
		"#Minh Râu#i",
		"#việt minh#i",
		"#việt cộng#i",
		"#địt#i",
		"#đéo#i",
		"#lồn#i",
		"#buồi#i",
		"#cặc#i",
		"#địt mẹ#i",
		"#lịt mẹ#i",
		"#đụ mạ#i",
		"#đù má#i",
		"#đụ mẹ#i",
		"#đéo mẹ#i",
		"#địt mẹ mày#i",
		"#đụ mạ mày#i",
		"#đù má mày#i",
		"#đụ mẹ mày#i",
		"#đéo mẹ mày#i",
		"#địt mẹ chúng mày#i",
		"#đụ mạ chúng mày#i",
		"#đù má chúng mày#i",
		"#đụ mẹ chúng mày#i",
		"#đéo mẹ chúng mày#i",
		"#lồn mẹ mày#i",
		"#tiên sư bố#i",
		"#tổ sư bố#i",
		"#mả mẹ mày#i",
		"#mả cha mày#i",
		"#mả bố mày#i",
		"#mả tổ mày#i",
		"#mả mẹ chúng mày#i",
		"#mả cha chúng mày#i",
		"#mả bố chúng mày#i",
		"#mả tổ chúng mày#i",
		"#lỗ đít#i",
		"#mặt lồn#i",
		"#liếm lồn#i",
		"#móc lồn#i",
		"#ăn lồn#i",
		"#mặt lìn#i",
		"#liếm lìn#i",
		"#móc lìn#i",
		"#ăn lìn#i",
		"#liếm đít#i",
		"#con phò#i",
		"#con đĩ#i",
		"#con điếm#i",
		"#đĩ đực#i",
		"#điếm đực#i",
		"#đồ chó#i",
		"#đồ lợn#i",
		"#liếm cứt#i",
		"#bốc cứt#i",
		"#ăn cứt#i",
		"#nhét cứt#i",
		"#ăn lồn#i",
		"#máu lồn#i",
		"#ăn buồi#i",
		"#mút buồi#i",
		"#ăn cặc#i",
		"#bú cặc#i",
		"#con cặc#i",
		"#mút cặc#i",
		"#ăn kặc#i",
		"#bú kặc#i",
		"#củ kặc#i",
		"#con kặc#i",
		"#mút kặc#i",
		"#ăn kẹc#i",
		"#bú kẹc#i",
		"#củ kẹc#i",
		"#con kẹc#i",
		"#bú dái#i",
		"#bú dzái#i",
		"#mút zái#i",
		"#bú buồi#i",
		"#đầu buồi#i",
		"#bú cu#i",
		"#bú ku#i",
		"#con ku#i",
		"#ĐỊT MẸ#i",
		"#DIT ME#i",
		"#Đy~ chó#i",
		"#Đĩ chó#i",
		"#ĂN KỨT#i",
		"#ăn kứt#i",
		"#ngứa dzái#i",
		"#bán dzâm#i",
		"#ngứa zdái#i",
		"#cờ ba sọc#i",
		"#cờ 3 sọc#i",
		"#nguoi-viet.com#i",
		"#bỏ mẹ#i",
		"#LỒN#i",
		"#CỨT#i",
		"#ĐỴT#i",
		"#ĐỊT#i",
		"#ĐĨ#i",
		"#ĐỈ#i",
		"#đĩ#i",
		"#đỉ#i",
		"#đĩ#i",
		"#loz`#i",
		"#đĩ?#i",
		"#đĨ#i",
		"#Địt mẹ#i",
		"#Địt#i",
		"#đỵt mẹ#i",
		"#đỵt#i",
		"#Đỵt mẹ#i",
		"#Đỵt#i",
		"#đỴt#i",
		"#nứng cẹc#i",
		"#nứng kẹt#i",
		"#dis mẹ#i",
		"#đis mẹ#i",
		"#đIs mẹ#i",
		"#đỤ mẸ#i",
		"#đéo#i",
		"#ĐỤ#i",
		"#đụ#i",
		"#ĐỊT#i",
		"#địt tổ#i",
		"#nứng#i",
		"#lồn#i",
		"#mất dạy#i",
		"#cave#i",
		"#nứng#i",
		"#địt#i",
		"#ngứa#i",
		"#nứng lồn#i",
		"#đéo#i",
		"#dis#i",
		"#hot^. le.#i",
		"#hột le#i",
		"#bu'#i",
		"#bú#i",
		"#Đjt#i",
		"#lỒn#i",
		"#đ ĩ#i",
		"#LỒN#i",
		"#deo'#i",
		"#liem^' #i",
		"#cho'#i",
		"#cut'#i",
		"#hiep' #i",
		"#trYm#i",
		"#đ ĩ #i",
		"#đ ĩ#i",
		"#mặt LỒN#i",
		"#ĐỴT#i",
		"#mje#i",
		"#khắm#i",
		"#trYm#i",
		"#ỈA#i",
		"#Đỵt mẸ#i",
		"#BUỒI#i",
		"#hãm#i",
		"#Cứt#i",
		"#CỨT#i",
		"#cứt#i",
		"#cỨt#i",
		"#cứT#i",
		"#CỨt#i",
		"#CPVNTD#i",
		"#sjp#i",
		"#ĐÝT#i",
		"#BUỒI#i",
		"#Dân Tộc#i",
		"#Amen#i",
		"#Đụ#i",
		"#ĐỊT#i",
		"#LO^`N#i",
		"#BUÔ`i#i",
		"#UCXK#i",
		"#SHIET#i",
		"#d!ck#i",
		"#đỤ#i",
		"#đ ĩ#i",
		"#éo#i",
		"#trYm#i",
		"#nứng#i",
		"#cặc#i",
		"#lồn#i",
		"#địt#i",
		"#đỊT#i",
		"#lÒl#i",
		"#đít#i",
		"#lỒn#i",
		"#ĐỴT#i",
		"#ĐỴT mje#i",
		"#Đỵt#i",
		"#Đỵt mẸ}{đ ĩ#i",
		"#ỈA#i",
		"#CỨT#i",
		"#cứt#i",
		"#dek#i",
		"#đéo#i",
		"#đek#i",
		"#chó đẻ#i",
		"#FUCK#i",
		"#loZ#i",
		"#chửi#i",
		"#đỊT#i",
		"#lÒl#i",
		"#mẹ mày#i",
		"#má mày#i",
		"#đần thối#i",
		"#MẤT DẠY#i",
		"#mất dạy#i",
		"#f.u.c.k#i",
		"#F.U.C.K#i",
		"#f u c k#i",
		"#MÁ MÀY#i",
		"#MẸ MÀY#i",
		"#con cac#i",
		"#Fuck#i",
		"#FucK#i",
		"#F U C K#i",
		"#đú#i",
		"#đỉ#i",
		"#đĩ#i",
		"#đỉ#i",
		"#xâm phạm chủ quyền#i",
		"#vú#i",
		"#dú#i",
		"#vãi#i",
		"#dY~#i",
		"#diE^n#i",
		"#cH0#i",
		"#cH0'#i",
		"#zú#i",
		"#fản động#i",
		"#phản động#i",
		"#wtf#i",
		"#WTF#i",
		"#djs#i",
		"#teensos.net#i",
		"#Vanga#i",
		"#kunsun121.110mb#i",
		"#ch.ó#i",
		"#F*ck#i",
		"#đ.é.o#i",
		"#kenh78#i",
		"#Kenh78#i",
		"#đít ghẻ#i",
		"#đ.e'o#i",
		"#x-manga.tk#i",
		"#vntab#i",
		"#vatgia#i",
		"#cashfiesta#i",
		"#CASHFIESTA#i",
		"#d-âm#i",
		"#bắc kỳ#i",
		"#c.ức #i",
		"#súc sinh#i",
		"#ch.ửi#i",
		"#4ton#i",
		"#phản quốc#i",
		"#sogood#i",
		"#gocvip#i",
		"#123doi#i",
		"#đé-o#i",
		"#đị...t#i",
		"#lode123.tk#i",
		"#Vãi lỒn#i"
	);
	
	public static $profanityFull = array(
		"#\bzả zách\b#i",
		"#\bvkl\b#i",
		"#\bc.hó\b#i",
		"#\blzzz\b#i",
		"#\bfuck\b#i",
		"#\bshit\b#i",
		"#\bbuồi\b#i",
		"#\bđịt\b#i",
		"#\bđụ\b#i",
		"#\bnứng\b#i",
		"#\blồn\b#i",
		"#\bfuck\b#i",
		"#\bfucking\b#i",
		"#\bcock\b#i",
		"#\bbitch\b#i",
		"#\bcặc\b#i",
		"#\bcặt\b#i",
		"#\bkặc\b#i",
		"#\bĐụ\b#i",
		"#\bđéo\b#i",
		"#\bsuck\b#i",
		"#\bdcm\b#i",
		"#\bDCM\b#i",
		"#\bvcl\b#i",
		"#\bbullshit\b#i",
		"#\bkhốn nạn\b#i",
		"#\bđụ má\b#i",
		"#\bĐĩ\b#i",
		"#\bđịt mẹ mày\b#i",
		"#\bđéo mẹ\b#i",
		"#\bđụ mẹ\b#i",
		"#\blồn mẹ\b#i",
		"#\blỗ đít\b#i",
		"#\bmóc lồn\b#i",
		"#\bliếm lồn\b#i",
		"#\băn lồn\b#i",
		"#\bliếm lìn\b#i",
		"#\bmặt lìn\b#i",
		"#\bcon phò\b#i",
		"#\bcon kặc\b#i",
		"#\bMinh Râu\b#i",
		"#\bviệt minh\b#i",
		"#\bviệt cộng\b#i",
		"#\bđịt\b#i",
		"#\bđéo\b#i",
		"#\blồn\b#i",
		"#\bbuồi\b#i",
		"#\bcặc\b#i",
		"#\bđịt mẹ\b#i",
		"#\blịt mẹ\b#i",
		"#\bđụ mạ\b#i",
		"#\bđù má\b#i",
		"#\bđụ mẹ\b#i",
		"#\bđéo mẹ\b#i",
		"#\bđịt mẹ mày\b#i",
		"#\bđụ mạ mày\b#i",
		"#\bđù má mày\b#i",
		"#\bđụ mẹ mày\b#i",
		"#\bđéo mẹ mày\b#i",
		"#\bđịt mẹ chúng mày\b#i",
		"#\bđụ mạ chúng mày\b#i",
		"#\bđù má chúng mày\b#i",
		"#\bđụ mẹ chúng mày\b#i",
		"#\bđéo mẹ chúng mày\b#i",
		"#\blồn mẹ mày\b#i",
		"#\btiên sư bố\b#i",
		"#\btổ sư bố\b#i",
		"#\bmả mẹ mày\b#i",
		"#\bmả cha mày\b#i",
		"#\bmả bố mày\b#i",
		"#\bmả tổ mày\b#i",
		"#\bmả mẹ chúng mày\b#i",
		"#\bmả cha chúng mày\b#i",
		"#\bmả bố chúng mày\b#i",
		"#\bmả tổ chúng mày\b#i",
		"#\blỗ đít\b#i",
		"#\bmặt lồn\b#i",
		"#\bliếm lồn\b#i",
		"#\bmóc lồn\b#i",
		"#\băn lồn\b#i",
		"#\bmặt lìn\b#i",
		"#\bliếm lìn\b#i",
		"#\bmóc lìn\b#i",
		"#\băn lìn\b#i",
		"#\bliếm đít\b#i",
		"#\bcon phò\b#i",
		"#\bcon đĩ\b#i",
		"#\bcon điếm\b#i",
		"#\bđĩ đực\b#i",
		"#\bđiếm đực\b#i",
		"#\bđồ chó\b#i",
		"#\bđồ lợn\b#i",
		"#\bliếm cứt\b#i",
		"#\bbốc cứt\b#i",
		"#\băn cứt\b#i",
		"#\bnhét cứt\b#i",
		"#\băn lồn\b#i",
		"#\bmáu lồn\b#i",
		"#\băn buồi\b#i",
		"#\bmút buồi\b#i",
		"#\băn cặc\b#i",
		"#\bbú cặc\b#i",
		"#\bcon cặc\b#i",
		"#\bmút cặc\b#i",
		"#\băn kặc\b#i",
		"#\bbú kặc\b#i",
		"#\bcủ kặc\b#i",
		"#\bcon kặc\b#i",
		"#\bmút kặc\b#i",
		"#\băn kẹc\b#i",
		"#\bbú kẹc\b#i",
		"#\bcủ kẹc\b#i",
		"#\bcon kẹc\b#i",
		"#\bbú dái\b#i",
		"#\bbú dzái\b#i",
		"#\bmút zái\b#i",
		"#\bbú buồi\b#i",
		"#\bđầu buồi\b#i",
		"#\bbú cu\b#i",
		"#\bbú ku\b#i",
		"#\bcon ku\b#i",
		"#\bĐỊT MẸ\b#i",
		"#\bDIT ME\b#i",
		"#\bĐy~ chó\b#i",
		"#\bĐĩ chó\b#i",
		"#\bĂN KỨT\b#i",
		"#\băn kứt\b#i",
		"#\bngứa dzái\b#i",
		"#\bbán dzâm\b#i",
		"#\bngứa zdái\b#i",
		"#\bcờ ba sọc\b#i",
		"#\bcờ 3 sọc\b#i",
		"#\bnguoi-viet.com\b#i",
		"#\bbỏ mẹ\b#i",
		"#\bLỒN\b#i",
		"#\bCỨT\b#i",
		"#\bĐỴT\b#i",
		"#\bĐỊT\b#i",
		"#\bĐĨ\b#i",
		"#\bĐỈ\b#i",
		"#\bđĩ\b#i",
		"#\bđỉ\b#i",
		"#\bđĩ\b#i",
		"#\bloz`\b#i",
		"#\bđĩ?\b#i",
		"#\bđĨ\b#i",
		"#\bĐịt mẹ\b#i",
		"#\bĐịt\b#i",
		"#\bđỵt mẹ\b#i",
		"#\bđỵt\b#i",
		"#\bĐỵt mẹ\b#i",
		"#\bĐỵt\b#i",
		"#\bđỴt\b#i",
		"#\bnứng cẹc\b#i",
		"#\bnứng kẹt\b#i",
		"#\bdis mẹ\b#i",
		"#\bđis mẹ\b#i",
		"#\bđIs mẹ\b#i",
		"#\bđỤ mẸ\b#i",
		"#\bđéo\b#i",
		"#\bĐỤ\b#i",
		"#\bđụ\b#i",
		"#\bĐỊT\b#i",
		"#\bđịt tổ\b#i",
		"#\bnứng\b#i",
		"#\blồn\b#i",
		"#\bmất dạy\b#i",
		"#\bcave\b#i",
		"#\bnứng\b#i",
		"#\bđịt\b#i",
		"#\bngứa\b#i",
		"#\bnứng lồn\b#i",
		"#\bđéo\b#i",
		"#\bdis\b#i",
		"#\bhot^. le.\b#i",
		"#\bhột le\b#i",
		"#\bbu'\b#i",
		"#\bbú\b#i",
		"#\bĐjt\b#i",
		"#\blỒn\b#i",
		"#\bđ ĩ\b#i",
		"#\bLỒN\b#i",
		"#\bdeo'\b#i",
		"#\bliem^' \b#i",
		"#\bcho'\b#i",
		"#\bcut'\b#i",
		"#\bhiep' \b#i",
		"#\btrYm\b#i",
		"#\bđ ĩ \b#i",
		"#\bđ ĩ\b#i",
		"#\bmặt LỒN\b#i",
		"#\bĐỴT\b#i",
		"#\bmje\b#i",
		"#\bkhắm\b#i",
		"#\btrYm\b#i",
		"#\bỈA\b#i",
		"#\bĐỵt mẸ\b#i",
		"#\bBUỒI\b#i",
		"#\bhãm\b#i",
		"#\bCứt\b#i",
		"#\bCỨT\b#i",
		"#\bcứt\b#i",
		"#\bcỨt\b#i",
		"#\bcứT\b#i",
		"#\bCỨt\b#i",
		"#\bCPVNTD\b#i",
		"#\bsjp\b#i",
		"#\bĐÝT\b#i",
		"#\bBUỒI\b#i",
		"#\bDân Tộc\b#i",
		"#\bAmen\b#i",
		"#\bĐụ\b#i",
		"#\bĐỊT\b#i",
		"#\bLO^`N\b#i",
		"#\bBUÔ`i\b#i",
		"#\bUCXK\b#i",
		"#\bSHIET\b#i",
		"#\bd!ck\b#i",
		"#\bđỤ\b#i",
		"#\bđ ĩ\b#i",
		"#\béo\b#i",
		"#\btrYm\b#i",
		"#\bnứng\b#i",
		"#\bcặc\b#i",
		"#\blồn\b#i",
		"#\bđịt\b#i",
		"#\bđỊT\b#i",
		"#\blÒl\b#i",
		"#\bđít\b#i",
		"#\blỒn\b#i",
		"#\bĐỴT\b#i",
		"#\bĐỴT mje\b#i",
		"#\bĐỵt\b#i",
		"#\bĐỵt mẸ}{đ ĩ\b#i",
		"#\bỈA\b#i",
		"#\bCỨT\b#i",
		"#\bcứt\b#i",
		"#\bdek\b#i",
		"#\bđéo\b#i",
		"#\bđek\b#i",
		"#\bchó đẻ\b#i",
		"#\bFUCK\b#i",
		"#\bloZ\b#i",
		"#\bchửi\b#i",
		"#\bđỊT\b#i",
		"#\blÒl\b#i",
		"#\bmẹ mày\b#i",
		"#\bmá mày\b#i",
		"#\bđần thối\b#i",
		"#\bMẤT DẠY\b#i",
		"#\bmất dạy\b#i",
		"#\bf.u.c.k\b#i",
		"#\bF.U.C.K\b#i",
		"#\bf u c k\b#i",
		"#\bMÁ MÀY\b#i",
		"#\bMẸ MÀY\b#i",
		"#\bcon cac\b#i",
		"#\bFuck\b#i",
		"#\bFucK\b#i",
		"#\bF U C K\b#i",
		"#\bđú\b#i",
		"#\bđỉ\b#i",
		"#\bđĩ\b#i",
		"#\bđỉ\b#i",
		"#\bxâm phạm chủ quyền\b#i",
		"#\bvú\b#i",
		"#\bdú\b#i",
		"#\bvãi\b#i",
		"#\bdY~\b#i",
		"#\bdiE^n\b#i",
		"#\bcH0\b#i",
		"#\bcH0'\b#i",
		"#\bzú\b#i",
		"#\bfản động\b#i",
		"#\bphản động\b#i",
		"#\bwtf\b#i",
		"#\bWTF\b#i",
		"#\bdjs\b#i",
		"#\bteensos.net\b#i",
		"#\bVanga\b#i",
		"#\bkunsun121.110mb\b#i",
		"#\bch.ó\b#i",
		"#\bF*ck\b#i",
		"#\bđ.é.o\b#i",
		"#\bkenh78\b#i",
		"#\bKenh78\b#i",
		"#\bđít ghẻ\b#i",
		"#\bđ.e'o\b#i",
		"#\bx-manga.tk\b#i",
		"#\bvntab\b#i",
		"#\bvatgia\b#i",
		"#\bcashfiesta\b#i",
		"#\bCASHFIESTA\b#i",
		"#\bd-âm\b#i",
		"#\bbắc kỳ\b#i",
		"#\bc.ức \b#i",
		"#\bsúc sinh\b#i",
		"#\bch.ửi\b#i",
		"#\b4ton\b#i",
		"#\bphản quốc\b#i",
		"#\bsogood\b#i",
		"#\bgocvip\b#i",
		"#\b123doi\b#i",
		"#\bđé-o\b#i",
		"#\bđị...t\b#i",
		"#\blode123.tk\b#i",
		"#\bVãi lỒn\b#i"
	);
	
	public static function countProfanity($originText)
	{
		$text = $originText;
		// first remove any potential html / scripting tags...
		$text = preg_replace('#<[^>]+>#' , '' , $text);
		
		// set variables and check for any profanity...
		$profanityCount1 = 0; // set complete-word profanity count to 0
		$profanityCount2 = 0; // set partial-word profanity count to 0
		
		$postProccess = preg_replace(self::$profanityFull, "*", $text, -1 , $profanityCount1);
		$text = $postProccess;
		
		// and then check for words that are partial in profanity...
		$postProccess = preg_replace(self::$profanityPatial, '*', $text, -1 , $profanityCount2);
		$text = $postProccess;
		unset($postProccess);
		
		// finally, remove any added slahes due to get_magic_quotes_gpc()...
		if(get_magic_quotes_gpc()){
		    $text = stripslashes($text);
		}
//		echo $text;
		return $profanityCount1 + $profanityCount2;
	}
}